apiVersion: apps/v1
kind: Deployment
metadata:
  name: beauty-deployment
  labels:
    app: beauty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beauty
  template:
    metadata:
      labels:
        app: beauty
    spec:
      containers:
      - name: beauty
        image: 508901769865.dkr.ecr.us-east-1.amazonaws.com/shopping-site-beauty:59da11d4f793ea1b9d4e0322e590ac55013ae718
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beauty-service
  labels:
    app: beauty
spec:
  type: ClusterIP
  selector:
    app: beauty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
